const contractAddress = "0xa7E9f79bFA960ea9B42AC17F688AeDeB2aBb4A75"; // Replace with your own contract address
const chain = 'goerli'; // goerli, polygon, or ethereum

const welcome_h1 = "Welcome to the Impulse Intelligence";
const welcome_h2 = "Connect MetaMask to get started";
const welcome_p = "IMPULSE INTELLIGENCE WILL LIVE SOON.";
const h1_presale_mint = "Pre-Sale Minting Open!!";
const h1_public_mint = "Public Minting Open!!";
const h2_presale_coming_soon = "Pre-Sale Minting Countdown";
const h2_presale_mint = "Pre-sale Minting Countdown";
const p_presale_coming_soon = "We are working hard to launch the NFT Collection. Stay tuned for updates!";
const p_presale_mint_not_whitelisted = "You are not whitelisted for the pre-sale..";
const p_presale_mint_whitelisted = "You're on the whitelist for the pre-sale! 🎉";
const p_presale_mint_already_minted = "You've already claimed your whitelist mint. Thank you! 🎉";
const p_public_mint = "No whitelist needed. Public minting is now open! 🎉";
const button_presale_coming_soon = "Get on the Whitelist";
const button_presale_mint_whitelisted = "Mint Your Special NFT";
const button_presale_mint_not_whitelisted = "Join the Discord";
const button_presale_already_minted = "Join The Community";
const button_public_mint = "Mint Your NFT";
const mint_failed = "Minting failed. Please try again.";
